# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {} is {} kilometers).format(planet,diameter)')


The diameter of {} is {} kilometers).format(planet,diameter)


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:

np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [3]:
import pandas as pd


In [9]:
data=[['kaviya',22],['divya',20],['gayathri',23]]
df=pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0    kaviya   22
1     divya   20
2  gayathri   23

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
import datetime
start=datetime.date(2023,1,1)
k=1
res=[]
for day in range(k):
  date=(start+datetime.timedelta(days=day)).isoformat()
  res.append(data)
print('series of dates from jan 1st 2023 to 10th feb:'+str(res))


series of dates from jan 1st 2023 to 10th feb:[[['kaviya', 22], ['divya', 20], ['gayathri', 23]]]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
df=pd.DataFrame(lists,columns=['x','y','z'])
df

x    y   z
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24